import test from 'node:test';
import assert from 'node:assert/strict';
import { randomUUID, createHash } from 'node:crypto';
import { mkdtempSync, rmSync, readFileSync, readdirSync } from 'node:fs';
import { join } from 'node:path';
import { tmpdir } from 'node:os';
import sharp from 'sharp';
import api from '../api.js';
import { openDatabase, migrate, checkSchema } from '../database.js';
import { createApplication } from '../server.js';
import { loadConfig } from '../config.js';
import { GAME_JAM_BODY_LIMIT } from '../covers.js';
const sha=bytes=>createHash('sha256').update(bytes).digest('hex');
const manifest={contract_version:'herstory-event-v1',app_id:'city_game',version:'1.0.0',save_quota_bytes:1024};
function form(options={}){const f=new FormData();for(const [key,value] of Object.entries({title:'城市相遇',author:'共创团队',description:'按键探索城市，留下相遇。',category:'城市社交',...options.fields}))f.set(key,value);f.set('manifest',new Blob([options.manifestText??JSON.stringify({...manifest,...options.manifest})],{type:'application/json'}),options.manifestName||'event-app.json');f.set('firmware',new Blob([options.bytes||Buffer.from([0xe9,1,2,3,4])]),options.fileName||'city-full.bin');if(options.cover)f.set('cover',new Blob([options.cover],{type:'image/png'}),'cover.png');return f}
function fixture(t){const dir=mkdtempSync(join(tmpdir(),'jam-test-')),path=join(dir,'jam.sqlite'),db=openDatabase(path);migrate(db);const stamp=Math.floor(Date.now()/1000),origin='http://127.0.0.1:3341';const env={DB:db,AUTH_PEPPER:'isolated-game-jam-test-pepper-00000000000',PUBLIC_ORIGIN:origin};t.after(()=>{db.close();rmSync(dir,{recursive:true,force:true})});function member(role='member'){const id=randomUUID(),token=sha(id);db.raw.prepare("INSERT INTO members(id,email,nickname,role,status,created_at,updated_at) VALUES(?,?,?,?,'active',?,?)").run(id,id+'@example.test','测试成员',role,stamp,stamp);db.raw.prepare('INSERT INTO sessions VALUES(?,?,?,?)').run(sha(token),id,stamp+3600,stamp);return {id,token}}
async function call(path,user,body,method=body?'POST':'GET',requestOrigin=origin){const multipart=body instanceof FormData;const response=await api.fetch(new Request(origin+path,{method,headers:{Origin:requestOrigin,...(user?{Cookie:'popup_city_session='+user.token}:{}),...(body&&!multipart?{'Content-Type':'application/json'}:{})},...(body?{body:multipart?body:JSON.stringify(body)}:{})}),env);const bytes=Buffer.from(await response.arrayBuffer()),json=response.headers.get('content-type')?.startsWith('application/json');return {status:response.status,headers:response.headers,bytes,data:json?JSON.parse(bytes.toString()):null}}
return {db,path,origin,member,call}}
test('Game Jam uses host membership, keeps submissions private and binds the authenticated owner',async t=>{const f=fixture(t),a=f.member(),b=f.member();assert.deepEqual((await f.call('/api/game-jam/projects')).data,{projects:[]});assert.equal((await f.call('/api/game-jam/mine')).status,401);assert.equal((await f.call('/api/game-jam/projects',null,form())).status,401);const forged=form();forged.set('owner_id',b.id);assert.equal((await f.call('/api/game-jam/projects',a,forged)).status,400);const created=await f.call('/api/game-jam/projects',a,form());assert.equal(created.status,201);assert.equal(created.data.project.owner_id,a.id);assert.equal(created.data.project.status,'pending');assert.equal((await f.call('/api/game-jam/projects')).data.projects.length,0);assert.equal((await f.call('/api/game-jam/mine',b)).data.projects.length,0);assert.equal((await f.call('/api/game-jam/mine',a)).data.projects.length,1);assert.equal((await f.call(created.data.project.firmware_url,b)).status,404);assert.equal((await f.call(created.data.project.firmware_url)).status,401)});
test('server validates firmware and manifests without leaving partial apps or files',async t=>{const f=fixture(t),a=f.member();for(const options of [{manifestText:'null'},{manifestText:'{'},{manifest:{contract_version:'wrong'}},{manifest:{app_id:'x'}},{manifest:{version:'1.0.0garbage'}},{manifest:{save_quota_bytes:2049}},{manifest:{save_quota_bytes:'12'}},{fileName:'app.bin'},{bytes:Buffer.from([0,1])},{bytes:Buffer.alloc(0x690000,0xe9)},{fields:{category:'未知'}}])assert.equal((await f.call('/api/game-jam/projects',a,form(options))).status,400,JSON.stringify({...options,bytes:undefined}));assert.equal(f.db.raw.prepare('SELECT COUNT(*) n FROM game_jam_apps').get().n,0);assert.equal(f.db.raw.prepare('SELECT COUNT(*) n FROM game_jam_projects').get().n,0)});
test('retries deduplicate the version and app IDs cannot be hijacked by another member',async t=>{const f=fixture(t),a=f.member(),b=f.member();const results=await Promise.all(Array.from({length:5},()=>f.call('/api/game-jam/projects',a,form())));assert.equal(results.filter(r=>r.status===201).length,1);assert.equal(new Set(results.map(r=>r.data.project.id)).size,1);assert.equal(f.db.raw.prepare('SELECT COUNT(*) n FROM game_jam_projects').get().n,1);assert.equal((await f.call('/api/game-jam/projects',a,form({fields:{title:'替换'}}))).status,409);assert.equal((await f.call('/api/game-jam/projects',b,form({manifest:{version:'2.0.0'}}))).status,409);assert.equal((await f.call('/api/game-jam/projects',a,form({manifest:{version:'2.0.0'}}))).status,201)});
test('review requires administrator, records evidence, gates gallery and preserves exact download bytes',async t=>{const f=fixture(t),a=f.member(),b=f.member(),admin=f.member('admin');const cover=await sharp({create:{width:8,height:8,channels:3,background:'#e7387a'}}).png().toBuffer();const created=await f.call('/api/game-jam/projects',a,form({cover})),p=created.data.project;assert.equal((await f.call(p.cover_url,b)).status,404);assert.equal((await f.call('/api/admin/game-jam/projects',a)).status,403);const route=`/api/admin/game-jam/projects/${p.id}/review`,review={status:'published',note:'分区与真机运行已核对（模拟验收）'};assert.equal((await f.call(route,b,review)).status,403);assert.equal((await f.call(route,admin,review,'POST','https://wrong.test')).status,403);assert.equal((await f.call(route,admin,{status:'published',note:''})).status,400);assert.equal((await f.call(route,admin,review)).status,200);await f.call(route,admin,review);assert.equal(f.db.raw.prepare('SELECT COUNT(*) n FROM game_jam_reviews').get().n,1);const gallery=(await f.call('/api/game-jam/projects')).data.projects;assert.equal(gallery.length,1);assert.equal('owner_id' in gallery[0],false);assert.equal('review_note' in gallery[0],false);assert.equal('firmware' in gallery[0],false);assert.equal((await f.call(p.cover_url)).headers.get('content-type'),'image/webp');const firmware=await f.call(p.firmware_url,b);assert.deepEqual(firmware.bytes,Buffer.from([0xe9,1,2,3,4]));assert.equal(sha(firmware.bytes),p.firmware_sha256);assert.equal(firmware.headers.get('x-content-sha256'),p.firmware_sha256);assert.deepEqual((await f.call(p.manifest_url,a)).data,manifest);await f.call(route,admin,{status:'rejected',note:'需调整分区'});assert.equal((await f.call('/api/game-jam/projects')).data.projects.length,0);assert.equal((await f.call(p.firmware_url,b)).status,404);assert.equal((await f.call(p.firmware_url,a)).status,200);assert.equal(f.db.raw.prepare('SELECT COUNT(*) n FROM game_jam_reviews').get().n,2);await f.call(route,admin,review);f.db.raw.prepare("UPDATE members SET status='disabled' WHERE id=?").run(a.id);assert.equal((await f.call('/api/game-jam/projects')).data.projects.length,0);assert.equal((await f.call(p.firmware_url,b)).status,404);assert.equal((await f.call(p.firmware_url,admin)).status,200)});
test('firmware, metadata and SHA persist across database connections',async t=>{const f=fixture(t),a=f.member();const saved=(await f.call('/api/game-jam/projects',a,form())).data.project;const reopened=openDatabase(f.path);try{checkSchema(reopened);const row=reopened.raw.prepare('SELECT firmware,firmware_sha256,manifest_json FROM game_jam_projects WHERE id=?').get(saved.id);assert.equal(sha(row.firmware),saved.firmware_sha256);assert.deepEqual(JSON.parse(row.manifest_json),manifest)}finally{reopened.close()}});
test('0011 migration preserves existing members, sessions and planets and does not seed fake works',()=>{const db=openDatabase(':memory:');try{db.raw.exec('PRAGMA application_id=1213219633;CREATE TABLE schema_migrations(name TEXT PRIMARY KEY,checksum TEXT NOT NULL)');for(const name of readdirSync(new URL('../migrations/',import.meta.url)).filter(n=>n.endsWith('.sql')&&!n.startsWith('0011')).sort()){const sql=readFileSync(new URL('../migrations/'+name,import.meta.url));db.raw.exec(sql.toString());db.raw.prepare('INSERT INTO schema_migrations VALUES(?,?)').run(name,sha(sql))}db.raw.prepare('INSERT INTO members(id,email,nickname,created_at,updated_at) VALUES(?,?,?,?,?)').run('existing','old@example.test','原有成员',1,1);db.raw.prepare('INSERT INTO sessions VALUES(?,?,?,?)').run('old-session','existing',9999999999,1);db.raw.prepare('INSERT INTO member_planets(member_id,planet_id,palette_id,created_at) VALUES(?,?,?,?)').run('existing','old-planet','green',1);migrate(db);checkSchema(db);migrate(db);assert.equal(db.raw.prepare('SELECT nickname FROM members WHERE id=?').get('existing').nickname,'原有成员');assert.equal(db.raw.prepare('SELECT token_hash FROM sessions').get().token_hash,'old-session');assert.equal(db.raw.prepare('SELECT planet_id FROM member_planets').get().planet_id,'old-planet');assert.equal(db.raw.prepare('SELECT COUNT(*) n FROM game_jam_projects').get().n,0)}finally{db.close()}});
test('HTTP bounds Game Jam uploads before parsing while normal login limits remain small',async t=>{const f=fixture(t),config=loadConfig({AUTH_PEPPER:'isolated-jam-http-test-pepper-000000000000',PUBLIC_ORIGIN:f.origin});const server=createApplication(config,{db:f.db,mailer:null});await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));t.after(async()=>{server.closeAllConnections();await new Promise(resolve=>server.close(resolve))});const response=await fetch(`http://127.0.0.1:${server.address().port}/api/game-jam/projects`,{method:'POST',headers:{Origin:f.origin,'Content-Type':'application/octet-stream'},body:Buffer.alloc(GAME_JAM_BODY_LIMIT+1)});assert.equal(response.status,413);await response.text();const page=await fetch(`http://127.0.0.1:${server.address().port}/game-jam.js`);assert.equal(page.status,200);await page.text()});
