import assert from 'node:assert/strict';
import { randomUUID, createHash } from 'node:crypto';
import { mkdirSync } from 'node:fs';
import { openDatabase, migrate } from '../database.js';
import { loadConfig } from '../config.js';
import { createApplication } from '../server.js';
const { chromium } = await import(process.env.PLAYWRIGHT_MODULE || 'playwright');
const origin='http://127.0.0.1:3334',out=process.env.BROWSER_OUTPUT||'/tmp/popup-planet-browser';mkdirSync(out,{recursive:true});
const db=openDatabase(':memory:');migrate(db);
const stamp=Math.floor(Date.now()/1000),messages=[],user=randomUUID(),friend=randomUUID();
for(const [id,name] of [[user,'新的邻居'],[friend,'星球伙伴']])db.raw.prepare("INSERT INTO members(id,email,nickname,status,created_at,updated_at) VALUES(?,?,?,'active',?,?)").run(id,id+'@example.test',name,stamp,stamp);
const device=randomUUID();db.raw.prepare('INSERT INTO devices VALUES(?,?,?,NULL,?)').run(device,user,'browser-device-test',stamp);
db.raw.prepare('INSERT INTO connections VALUES(?,?,?,?,?,?)').run(randomUUID(),user,friend,device,stamp,randomUUID());
const config=loadConfig({AUTH_PEPPER:'isolated-browser-planet-pepper-0000000000',PUBLIC_ORIGIN:origin,FROM_EMAIL:'noreply@example.test'});
const server=createApplication(config,{db,mailer:{send:async message=>messages.push(message)}});
await new Promise(resolve=>server.listen(3334,'127.0.0.1',resolve));
let browser;
try{
 browser=await chromium.launch({headless:true,...(process.env.CHROMIUM_PATH?{executablePath:process.env.CHROMIUM_PATH}:{}),args:['--enable-unsafe-swiftshader']});
 const context=await browser.newContext({viewport:{width:1280,height:1000}}),page=await context.newPage(),errors=[];
 page.on('pageerror',e=>errors.push(e.message));
 await page.goto(origin+'/#planet');await page.getByRole('button',{name:'用邮箱登录 ↗'}).click();
 await page.locator('#login-request-form input').fill(user+'@example.test');await page.getByRole('button',{name:'获取登录邮件',exact:true}).click();
 const code=/验证码是 (\d{6})/.exec(messages[0].text)[1];await page.locator('#login-code-form input').fill(code);await page.locator('#login-code-form button').click();
 await page.waitForURL('**/#setup');await page.locator('#profile-setup-form').waitFor();
 assert.equal(await page.locator('#planet-frame').count(),0);
 await page.locator('#profile-setup-form input[name=nickname]').fill('只设置一次');await page.locator('#profile-setup-form textarea[name=bio]').fill('一起建造和学习');
 await page.screenshot({path:out+'/first-login-profile-desktop.png',fullPage:true});
 await page.setViewportSize({width:390,height:844});assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));
 await page.screenshot({path:out+'/first-login-profile-mobile.png',fullPage:true});
 await page.getByRole('button',{name:'下一步：设置头像',exact:true}).click();await page.waitForFunction(()=>avatarEditor?.ready);
 await page.getByRole('button',{name:'下一步：确认资料',exact:true}).click();
 assert.equal(await page.locator('#profile-form input[name=nickname]').inputValue(),'只设置一次');
 assert.equal(await page.locator('#profile-form textarea[name=bio]').inputValue(),'一起建造和学习');
 await page.screenshot({path:out+'/profile-confirm-mobile.png',fullPage:true});
 await page.getByRole('button',{name:'确认头像并保存资料',exact:true}).click();await page.waitForURL('**/#planet/welcome');
 await page.locator('#planet-frame').waitFor();await page.setViewportSize({width:1280,height:1000});
 let frame=page.frameLocator('#planet-frame');await frame.locator('#world').waitFor({state:'attached'});assert.equal(await frame.locator('#host-pixel-canvas, [data-planet-mode], #pixel-pane').count(),0);
 await page.waitForFunction(()=>document.querySelector('#planet-loading').hidden);
 const identity=await frame.locator('body').evaluate(()=>window.HerstoryIdentity.getProfile());assert.equal(identity.userId,user);assert.ok(identity.planetId);
 assert.equal(await frame.locator('body').evaluate(()=>window.HerstoryApp.getState().demo),false);
 assert.equal(await frame.locator('body').evaluate(()=>window.HerstoryApp.getState().snapshot.connections.length),1);
 await page.waitForFunction(()=>!document.querySelector('#toast').classList.contains('visible'));
 await page.screenshot({path:out+'/planet-desktop.png',fullPage:true});
 await page.setViewportSize({width:390,height:844});
 assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));
 await page.reload();await page.waitForFunction(()=>document.querySelector('#planet-loading')?.hidden);
 frame=page.frameLocator('#planet-frame');assert.deepEqual(await frame.locator('body').evaluate(()=>window.HerstoryIdentity.getProfile()),identity);
 await page.locator('#planet-frame').scrollIntoViewIfNeeded();await frame.getByRole('button',{name:'星域',exact:true}).click();await page.screenshot({path:out+'/planet-mobile-field.png',fullPage:true});
 await page.getByRole('button',{name:'开始探索我的星球 ↗',exact:true}).click();await page.waitForURL('**/#planet');await page.goto(origin+'/#me');
 await page.locator('.profile-lock-note').waitFor();assert.equal(await page.locator('[data-action=edit-avatar]').count(),0);
 const forbidden=await page.evaluate(async()=>{const r=await fetch('/api/me',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({avatar:{}})});return r.status});assert.equal(forbidden,409);
 const savedAvatar=await page.evaluate(()=>JSON.stringify(state.me.avatar));
 await page.getByRole('button',{name:'编辑个人资料',exact:true}).click();await page.locator('#profile-form input[name=nickname]').fill('资料可编辑');await page.locator('#profile-form textarea[name=bio]').fill('头像不会变化');await page.getByRole('button',{name:'保存资料',exact:true}).click();await page.waitForFunction(()=>state.me.nickname==='资料可编辑');assert.equal(await page.evaluate(()=>JSON.stringify(state.me.avatar)),savedAvatar);
 await page.reload();await page.locator('.profile-lock-note').waitFor();assert.equal(await page.locator('.profile-head h1').textContent(),'资料可编辑');await page.screenshot({path:out+'/profile-locked-mobile.png',fullPage:true});
 // A different browser/session sees the same persistent planet, but another member does not.
 const second=await browser.newContext();await second.addCookies(await context.cookies());const p2=await second.newPage();await p2.goto(origin+'/#planet');await p2.waitForFunction(()=>document.querySelector('#planet-loading')?.hidden);
 assert.deepEqual(await p2.frameLocator('#planet-frame').locator('body').evaluate(()=>window.HerstoryIdentity.getProfile()),identity);
 // Removing the session must clear the embedded private view at the next state refresh.
 await context.request.post(origin+'/api/auth/logout',{headers:{Origin:origin}});
 await p2.frameLocator('#planet-frame').locator('body').evaluate(()=>window.HerstoryApp.refresh());
 await p2.getByRole('button',{name:'用邮箱登录 ↗'}).waitFor();assert.equal(await p2.locator('#planet-frame').count(),0);
 assert.deepEqual(errors,[]);
 console.log('PASS: login→personal information→one-time avatar→planet, persistent identity, real connections, website 3D only, mobile layout, editable profile and immutable avatar and expired-session clearing');
 console.log(out);
 await second.close();await context.close();
}finally{await browser?.close();server.closeAllConnections();await new Promise(resolve=>server.close(resolve));db.close();}
